config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'cushions#top'
  #get  'settings' =>  'settings#settings'
  #post 'settings' =>  'settings#create'
  #get  'tutorial' =>  'settings#tutorial'
  #get  'app' => 'app#top'
  get  'reset' => 'reset#hoge'
  get  'checkpants' => 'checkpants#getFewpantsToken'

  namespace :api, { format: 'json' } do
    resource :token, only: [:create]
    post 'update'   => 'items#updatepants'
    get  'items'    => 'items#index'
    post 'items'    => 'items#create'
    get  'weathers' => 'weathers#index'

    get  'notification' => 'notification#get'
    post 'notification' => 'notification#push'
  end

  #get 'Weather' => 'weather#controller'

  # redirect to root if user directly access to /settings
  get  'settings' => redirect('/')
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def settings
    @item = current_user.items.build if logged_in?
  end

  def tutorial
    # query init = true
    @data = params[:init]
  end

  def create
    item = current_user.items.build(item_params)
    item.name = "pants"

    if item.save
      redirect_to app_path
    else
      render 'settings'
    end
  end

  private
    def item_params
      params.require(:item).permit(:max, :current)
    end
end

app/views/settings/settings.html.erb
設定

<%= form_for(@item, url: settings_path) do |f| %>
  <%= f.label :max, "please fill in the number of your total pants" %>
  <%= f.number_field :max %>

  <%= f.label :current, "please fill in the number of your clean pants" %>
  <%= f.number_field :current %>

  <%= f.submit "OK", class: "btn btn-primary" %>
<% end %>

app/views/settings/tutorial.html.erb
チュートリアル

<% if @data %>
  <a href="/settings"><button>next</button></a>
<% end %>